Repository talmolab/sleap, pull requests merged in 2024-12, with the labels that each got.

#2038 [MV] Do not sort keys when loading calibration toml
  sleap/io/cameras.py
  tests/io/test_cameras.py
Labels: MultiView Stack

#1797 Add menu item for deleting instances beyond frame limit
  sleap/config/frame_range_form.yaml
  sleap/gui/app.py
  sleap/gui/commands.py
  sleap/gui/dialogs/frame_range.py
  tests/gui/test_commands.py
Labels: 2024-hackathon

#2058 Enable touchpad pinch to zoom
  sleap/gui/widgets/video.py
Labels: 2024-hackathon

#2052 Separate the video name and its filepath columns in `VideoTablesModel`
  sleap/gui/dataviews.py
Labels: enhancement, 2024-hackathon

#2063 Make status bar dependent on UI mode
  sleap/gui/app.py
Labels: 2024-hackathon
