Repository talmolab/sleap, pull requests merged in 2024-01, with the labels that each got.

#1628 PR4: Add helpmenu option
  sleap/gui/app.py
  sleap/gui/commands.py
Labels: bulletin

#1605 (3d -> 3c) Add method for multi instance products
  sleap/gui/commands.py
  tests/gui/test_commands.py
Labels: MultiView Stack

#1599 (3c -> 3b) Add method to test instance grouping
  sleap/gui/commands.py
  tests/gui/test_commands.py
Labels: MultiView Stack

#1586 (3b -> 3a) Add method to get single instance permutations
  sleap/gui/commands.py
  tests/gui/test_commands.py
Labels: MultiView Stack

#1673 Add ABL:AOC 2023 Workshop link
  .github/workflows/website.yml
  README.rst
Labels: documentation
