Repository talmolab/sleap, pull requests merged in 2025-04, with the labels that each got.

#2147 MV: Add a general precull iou threshold
  docs/guides/cli.md
  sleap/nn/tracker/components.py
  sleap/nn/tracking.py
  tests/nn/test_inference.py
  tests/nn/test_tracker_components.py
Labels: MultiView Stack

#2072 Ctrl + Click and Drag to copy instance
  docs/guides/gui.md
  sleap/gui/widgets/video.py
Labels: enhancement, 2024-hackathon, april-2025-hackathon

#1302 Allow tracking on `Instance`s (by adding `Instance.tracking_score`)
  sleap/info/write_tracking_h5.py
  sleap/instance.py
  sleap/io/format/hdf5.py
  sleap/io/format/nix.py
  sleap/nn/tracking.py
  tests/io/test_dataset.py
Labels: Re-tracking Spread, april-2025-hackathon
